services:

  # ==========================================
  # 1. DATABASES & BROKERS (The Foundation)
  # ==========================================
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  # ==========================================
  # 2. THE MICROSERVICES (The Brains)
  # ==========================================
  auth-service:
    build: ./auth_service
    ports:
      - "5001:5001"
    environment:
      - PYTHONUNBUFFERED=1

  product-service:
    build: ./product_service
    ports:
      - "5002:5002"
    depends_on:
      - elasticsearch
    environment:
      - PYTHONUNBUFFERED=1

  order-service:
    build: ./order_service
    ports:
      - "5003:5003"
    depends_on:
      - redis
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  # ==========================================
  # 3. BACKGROUND WORKERS (The Muscles)
  # ==========================================
  inventory-worker:
    build: ./product_service
    command: python inventory_worker.py
    depends_on:
      - rabbitmq
    restart: on-failure

  # ==========================================
  # 4. API GATEWAY (The Front Door)
  # ==========================================
  api-gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
      - product-service
      - order-service
    environment:
      - PYTHONUNBUFFERED=1

  # ==========================================
  # 5. FRONTEND (The UI)
  # ==========================================
  frontend:
    build: ./shopsphere-vanilla
    ports:
      - "5500:5500"
    environment:
      - PYTHONUNBUFFERED=1